import { ProductItem } from "../productItem.model";

export const products: ProductItem[] = [
  {
  id: 0,
  title: 'Beats Headphones',
  description: 'Test our new product',
  image: 'https://elcopcbonline.com/photos/product/4/176/4.jpg',
  width: '200',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '200',
  newPrice: '199'
}, 
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
{
  id: 1,
  title: 'Iphone 7 Case',
  description: 'Test our new product',
  image: 'https://icdn2.digitaltrends.com/image/digitaltrends/photo-mar-24-1-15-30-pm-edited-1.jpg',
  width: '100',
  length: '10',
  color: 'red',
  depth: '3',
  features: 'No Features',
  originalPrice: '17',
  newPrice: '14'
},
];
